/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppMarketplaceRouteImport } from './routes/app.marketplace'
import { Route as AppBuilderRouteImport } from './routes/app.builder'
import { Route as AppRunsIdRouteImport } from './routes/app.runs.$id'
import { Route as AppAgentsIdRouteImport } from './routes/app.agents.$id'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketplaceRoute = AppMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AppRoute,
} as any)
const AppBuilderRoute = AppBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => AppRoute,
} as any)
const AppRunsIdRoute = AppRunsIdRouteImport.update({
  id: '/runs/$id',
  path: '/runs/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsIdRoute = AppAgentsIdRouteImport.update({
  id: '/agents/$id',
  path: '/agents/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/builder': typeof AppBuilderRoute
  '/app/marketplace': typeof AppMarketplaceRoute
  '/app/': typeof AppIndexRoute
  '/app/agents/$id': typeof AppAgentsIdRoute
  '/app/runs/$id': typeof AppRunsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/builder': typeof AppBuilderRoute
  '/app/marketplace': typeof AppMarketplaceRoute
  '/app': typeof AppIndexRoute
  '/app/agents/$id': typeof AppAgentsIdRoute
  '/app/runs/$id': typeof AppRunsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/builder': typeof AppBuilderRoute
  '/app/marketplace': typeof AppMarketplaceRoute
  '/app/': typeof AppIndexRoute
  '/app/agents/$id': typeof AppAgentsIdRoute
  '/app/runs/$id': typeof AppRunsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/builder'
    | '/app/marketplace'
    | '/app/'
    | '/app/agents/$id'
    | '/app/runs/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/builder'
    | '/app/marketplace'
    | '/app'
    | '/app/agents/$id'
    | '/app/runs/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/builder'
    | '/app/marketplace'
    | '/app/'
    | '/app/agents/$id'
    | '/app/runs/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/marketplace': {
      id: '/app/marketplace'
      path: '/marketplace'
      fullPath: '/app/marketplace'
      preLoaderRoute: typeof AppMarketplaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/builder': {
      id: '/app/builder'
      path: '/builder'
      fullPath: '/app/builder'
      preLoaderRoute: typeof AppBuilderRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/runs/$id': {
      id: '/app/runs/$id'
      path: '/runs/$id'
      fullPath: '/app/runs/$id'
      preLoaderRoute: typeof AppRunsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agents/$id': {
      id: '/app/agents/$id'
      path: '/agents/$id'
      fullPath: '/app/agents/$id'
      preLoaderRoute: typeof AppAgentsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBuilderRoute: typeof AppBuilderRoute
  AppMarketplaceRoute: typeof AppMarketplaceRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAgentsIdRoute: typeof AppAgentsIdRoute
  AppRunsIdRoute: typeof AppRunsIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBuilderRoute: AppBuilderRoute,
  AppMarketplaceRoute: AppMarketplaceRoute,
  AppIndexRoute: AppIndexRoute,
  AppAgentsIdRoute: AppAgentsIdRoute,
  AppRunsIdRoute: AppRunsIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
